apiVersion: v1
kind: Service
metadata:
  name: greet-app-service
  labels:
    app: greet-app 
spec:
  selector:
    app: greet-app

  ports:
    - port: 8080
      targetPort: 8080

  type: LoadBalancer
